import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-6xl font-bold uppercase px-5 flex flex-col items-center justify-center h-screen">
        <p>
          Coming Soon
        </p>
      </main>
    </div>
  )
}
